# Generated by Django 6.0.7 on 2026-07-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='titulo',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(default='General', max_length=50, verbose_name='Categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(default='Producto Nuevo', max_length=100, verbose_name='Nombre del Artículo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
